<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <NoWarn>$(NoWarn);NU5118</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Umbraco.Community.Cloud.HealthChecks</PackageId>
    <Product>Umbraco.Community.Cloud.HealthChecks</Product>
    <Title>Umbraco Cloud Health Checks</Title>
    <PackageTags>umbraco plugin package umbraco-marketplace cloud health checks</PackageTags>
    <PackageDescription>A package for adding Umbraco Cloud health checks</PackageDescription>
    <RepositoryUrl>https://github.com/CrumpledDog/Umbraco.Community.Cloud.HealthChecks</RepositoryUrl>
    <PackageIcon>cloud-healthchecks.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Company>Crumpled Dog and Umbraco Community</Company>
    <PackageVersion>$(PackageVersion)</PackageVersion>
    <Version>$(PackageVersion)</Version>
    <FileVersion>$(FileVersionNumber)</FileVersion>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Authors>Crumpled Dog and Umbraco Community</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="[17.0.0,)" />
  </ItemGroup>

  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
      <Content Include="buildTransitive\**" PackagePath="buildTransitive" />
      <Content Include="appsettings-schema.Umbraco.Community.Cloud.HealthChecks.json" PackagePath="" />
      <Content Include="wwwroot\**" />
      <Content Include="Views\**\*.cshtml" />
  </ItemGroup>

  <ItemGroup>
      <None Update="cloud-healthchecks.png">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
     <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
